# Generated by Django 2.2.4 on 2022-04-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='isAccepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
